[package]
name = "smolder-proto"
version = "0.1.0"
edition = "2021"
authors = ["M00NLIG7"]
description = "Smolder proto - Part of the Smolder SMB toolkit"
repository = "https://github.com/M00NLIG7/smolder"
license = "MIT"
