ARG CROSS_BASE_IMAGE=ghcr.io/cross-rs/x86_64-pc-windows-gnu:main
FROM ${CROSS_BASE_IMAGE}

ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
    CARGO_HTTP_CAINFO=/etc/ssl/certs/ca-certificates.crt \
    NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
